name: Build Next.js client for course project
on: push
jobs:
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
    - name: Checkout node
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build client assets
      run: npm run build
    - name: Prepare files for archiving
      run: |
        mkdir -p dist
        cp -r .next/standalone/* dist/
        mkdir -p dist/.next/static
        cp -r .next/static/* dist/.next/static/
        mkdir -p dist/public
        cp -r src/public/* dist/public/
        zip -r site.zip dist
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: site.zip
  release-client:
    name: Release client
    needs: build-client
    runs-on: ubuntu-latest
    steps:
    - name: Download archive
      uses: actions/download-artifact@v4
      with:
        name: site
        path: ./
    - name: List files after download
      run: ls -l
    - name: Check if site.zip exists
      run: |
        if [ -f ./site.zip ]; then
          echo "site.zip exists"
        else
          echo "site.zip does not exist"
          exit 1
        fi
    - name: Create GitHub Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./site.zip
        asset_name: site-v${{ github.run_number }}.zip
        asset_content_type: application/zip